-- 建立PCM專用用戶和權限
-- 此腳本會在Oracle容器啟動時自動執行

-- 建立PCM用戶
CREATE USER pcm_user IDENTIFIED BY pcm_pass123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- 授予基本權限
GRANT CONNECT, RESOURCE TO pcm_user;

-- 授予建立物件的權限
GRANT CREATE TABLE TO pcm_user;
GRANT CREATE VIEW TO pcm_user;
GRANT CREATE SEQUENCE TO pcm_user;
GRANT CREATE TRIGGER TO pcm_user;
GRANT CREATE PROCEDURE TO pcm_user;
GRANT CREATE FUNCTION TO pcm_user;
GRANT CREATE PACKAGE TO pcm_user;
GRANT CREATE TYPE TO pcm_user;
GRANT CREATE SYNONYM TO pcm_user;
GRANT CREATE INDEX TO pcm_user;

-- 授予系統權限（用於遷移）
GRANT ALTER SESSION TO pcm_user;
GRANT CREATE SESSION TO pcm_user;

-- 允許查看系統表（用於遷移追蹤）
GRANT SELECT ON dba_tables TO pcm_user;
GRANT SELECT ON dba_tab_columns TO pcm_user;
GRANT SELECT ON dba_constraints TO pcm_user;
GRANT SELECT ON dba_indexes TO pcm_user;

-- 建立PCM Schema的基本結構
CONNECT pcm_user/pcm_pass123@//localhost:1521/XE

-- 建立遷移追蹤表
CREATE TABLE migration_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_name VARCHAR2(255) NOT NULL,
    executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    success NUMBER(1) DEFAULT 1 CHECK (success IN (0, 1)),
    error_message CLOB,
    CONSTRAINT uk_migration_script UNIQUE (script_name)
);

-- 建立系統資訊表
CREATE TABLE system_info (
    key_name VARCHAR2(100) PRIMARY KEY,
    key_value VARCHAR2(4000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 插入初始版本資訊
INSERT INTO system_info (key_name, key_value) VALUES ('schema_version', '1.0.0');
INSERT INTO system_info (key_name, key_value) VALUES ('migration_status', 'initialized');

COMMIT;

-- 顯示建立結果
SELECT 'PCM用戶建立完成' AS status FROM dual;
SELECT 'Migration tables created' AS status FROM dual;