services:
  # Oracle XE Database for PCM
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: pcm-oracle-dev
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD:-Oracle123}
      ORACLE_DATABASE: ${ORACLE_DATABASE:-pcm_db}
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "${ORACLE_PORT:-1521}:1521"
      - "${ORACLE_WEB_PORT:-5500}:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - pcm_network
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/${ORACLE_PASSWORD:-Oracle123}@//localhost:1521/XE", "@/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # SQL Developer Web (Optional Oracle Management Interface)
  oracle-web:
    image: gvenzl/oracle-xe:21-slim
    container_name: pcm-oracle-web
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD:-Oracle123}
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - pcm_network
    ports:
      - "${ORACLE_APEX_PORT:-8080}:8080"
    command: >
      bash -c "
        echo 'Enabling APEX and SQL Developer Web...'
        sqlplus -s system/${ORACLE_PASSWORD:-Oracle123}@oracle-db:1521/XE <<EOF
        ALTER USER APEX_PUBLIC_USER ACCOUNT UNLOCK;
        ALTER USER APEX_PUBLIC_USER IDENTIFIED BY ${ORACLE_PASSWORD:-Oracle123};
        exec ords_admin.enable_schema(p_enabled => TRUE, p_schema => 'HR', p_url_mapping_type => 'BASE_PATH', p_url_mapping_pattern => 'hr', p_auto_rest_auth => FALSE);
        commit;
        EXIT;
        EOF
      "
    profiles:
      - web-tools

networks:
  pcm_network:
    driver: bridge

volumes:
  oracle_data:
    driver: local
